### ISSUE TITLE
Error Updating

### ISSUE THREAD

**Issue by chrisfox75** [agneevX/my-ha-setup#5]
**Describe the bug**
Information is from Log Viewer in HA

Cannot connect to host raw.githubusercontent.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate

**To Reproduce**

Run Update on HA

**Expected behavior**

Should update, system stuck in Pending Update State even after a restart

**Screenshots**

Pending updates
My Ha Setup
You are running version 21fb105, version 932e230 is available

**Desktop (please complete the following information):**
 - Browser Chrome, latest version

**Physical Server Configuration**

Running Home Assistant on VMWare Guest verion 7

No connection problems at this time

**Comment by agneevX** [comment]
I'm sorry but where are you seeing this issue?

**Comment by chrisfox75** [comment]
****

Sorry here is a screenshot, the error is showing up in the log file, it just stays at pending update

(url)https://imgur.com/YD7VuSS

**Comment by agneevX** [comment]
Oh, my repo isn't meant to be installed. I haven't created it in that manner and unsure of the consequences. It's best to uninstall it, and copy paste lines from the YAML.

**Comment by chrisfox75** [comment]
Strange thing is it has been working fine all of a sudden it wont update, not sure why but why does HACS allow it to be installed then ??

**Comment by chrisfox75** [comment]
[HACS Install]https://imgur.com/oH4Xxcp

**Comment by agneevX** [comment]
Did you add it as a custom repository?

**Comment by chrisfox75** [comment]
Think so...

**Comment by chrisfox75** [comment]
If thats the cause i will reinstall it manually

**Comment by agneevX** [comment]
I just pushed 5bfec86. Please check and see if it fixes it.

**Comment by chrisfox75** [comment]
Well so much for that i removed it since i was going to manually install it now i cannot readd it back into HACS

Error i get now for the repo is
Repostitory structure for master is not compliant

Using your repo url of https://github.com/agneevX/my-ha-setup

**Comment by agneevX** [comment]
Did you select `Theme` in HACS?

**Comment by chrisfox75** [comment]
I really dont think this is a problem with your addon i think it has something to do with github or my configuration on this end, ill have to look into it, im getting a certificate error trying to install another addon also.. ill look into it and report back

**Comment by chrisfox75** [comment]
Sorry for the headache turns out my firewall was filtering githubcontent.com, if fixed the issue and now everything works fine

Thanks for your prompt help and assistance
Chris

**Comment by agneevX** [comment]
No problem, thanks for using my theme.
