### ISSUE TITLE
Hi -- you have username/password in your config file

### ISSUE THREAD

**Issue by yieldhog** [agneevX/my-ha-setup#6]
https://github.com/agneevX/my-ha-setup/blob/e69897720efa20958c4e7afa743f5e013fb579ce/config/configuration.yaml#L126

**Comment by agneevX** [comment]
This is intentional :)

**Comment by yieldhog** [comment]
Ah okay, figured you may want to put into secrets file, no worries.

**Comment by agneevX** [comment]
On second thought, I'll move it to secrets.yaml (and change the password!)
